// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"首页","path":"/home","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"用户管理","path":"/users","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"用户列表","path":"/users/list","parentId":"3","id":"4"},"5":{"name":"路线管理","path":"/routes","parentId":"ant-design-pro-layout","id":"5"},"6":{"name":"路线列表","path":"/routes/list","parentId":"5","id":"6"},"7":{"name":"新建路线","path":"/routes/edit","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"7"},"8":{"name":"编辑路线","path":"/routes/edit/:id","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"8"},"9":{"name":"订单管理","path":"/orders","parentId":"ant-design-pro-layout","id":"9"},"10":{"name":"排期管理","path":"/schedules","parentId":"ant-design-pro-layout","id":"10"},"11":{"name":"评价管理","path":"/evaluations","parentId":"ant-design-pro-layout","id":"11"},"12":{"name":"宠物档案","path":"/pets","parentId":"ant-design-pro-layout","id":"12"},"13":{"name":"出行人管理","path":"/travelers","parentId":"ant-design-pro-layout","id":"13"},"14":{"name":"财务管理","path":"/finance","parentId":"ant-design-pro-layout","id":"14"},"15":{"name":"系统设置","path":"/settings","parentId":"ant-design-pro-layout","id":"15"},"16":{"name":"操作日志","path":"/logs","parentId":"ant-design-pro-layout","id":"16"},"17":{"name":"内容管理","path":"/articles","parentId":"ant-design-pro-layout","id":"17"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Users__List" */'@/pages/Users/List.tsx')),
'5': React.lazy(() => import('./EmptyRoute')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Routes__List" */'@/pages/Routes/List.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Routes__Edit" */'@/pages/Routes/Edit.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Routes__Edit" */'@/pages/Routes/Edit.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Orders__index" */'@/pages/Orders/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Schedules__index" */'@/pages/Schedules/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Evaluations__index" */'@/pages/Evaluations/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__Pets__index" */'@/pages/Pets/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__Travelers__index" */'@/pages/Travelers/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__Finance__index" */'@/pages/Finance/index.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__Settings__index" */'@/pages/Settings/index.tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__Logs__index" */'@/pages/Logs/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__Articles__index" */'@/pages/Articles/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'D:/projects/frontend/admin/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
