-- 订单模块初始化脚本
-- 创建订单表
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  order_no VARCHAR(32) NOT NULL COMMENT '订单号 QD202404071755001',
  user_id BIGINT UNSIGNED NOT NULL,
  schedule_id BIGINT UNSIGNED NOT NULL COMMENT '排期ID',
  route_id BIGINT UNSIGNED NOT NULL,
  route_name VARCHAR(100) COMMENT '冗余路线名',
  travel_date DATE COMMENT '出行日期',
  participant_count INT DEFAULT 1 COMMENT '成人数量',
  pet_count INT DEFAULT 1 COMMENT '宠物数量',
  participants JSON COMMENT '参与人宠详情',
  route_price DECIMAL(10,2) COMMENT '路线单价',
  insurance_price DECIMAL(10,2) DEFAULT 0 COMMENT '保险费用',
  equipment_price DECIMAL(10,2) DEFAULT 0 COMMENT '装备租赁',
  total_amount DECIMAL(10,2) COMMENT '应付总额',
  discount_amount DECIMAL(10,2) DEFAULT 0 COMMENT '优惠金额',
  pay_amount DECIMAL(10,2) COMMENT '实付金额',
  status TINYINT DEFAULT 10 COMMENT '10待支付 20已支付 30已取消 40退款中 50已退款 60已完成 70已评价',
  pay_time TIMESTAMP NULL COMMENT '支付时间',
  pay_channel VARCHAR(20) COMMENT 'wechat/alipay',
  pay_transaction_id VARCHAR(64) COMMENT '第三方支付流水',
  refund_amount DECIMAL(10,2) DEFAULT 0,
  refund_reason VARCHAR(500),
  refund_time TIMESTAMP NULL,
  remark VARCHAR(500) COMMENT '用户备注',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_order_no (order_no),
  KEY idx_user_status (user_id, status),
  KEY idx_schedule (schedule_id),
  KEY idx_status (status),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单表';
