-- 地图模块初始化脚本
-- 创建POI地点表
CREATE TABLE IF NOT EXISTS poi_spots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL COMMENT '场所名称',
  poi_type TINYINT NOT NULL COMMENT '1酒店 2餐厅 3公园 4景点 5医院 6服务区',
  category VARCHAR(50) COMMENT '细分标签',
  province VARCHAR(50),
  city VARCHAR(50),
  district VARCHAR(50),
  address VARCHAR(200),
  longitude DECIMAL(10,7) COMMENT '经度',
  latitude DECIMAL(10,7) COMMENT '纬度',
  geohash VARCHAR(12) COMMENT '地理哈希',
  pet_level TINYINT DEFAULT 1 COMMENT '1允许 2友好 3亲宠',
  pet_facilities JSON COMMENT '设施列表',
  pet_policy TEXT COMMENT '宠物政策说明',
  pet_fee VARCHAR(100) COMMENT '宠物费用说明',
  images JSON COMMENT '环境照片',
  phone VARCHAR(20),
  business_hours VARCHAR(100),
  rating DECIMAL(2,1) DEFAULT 5.0 COMMENT '评分',
  review_count INT DEFAULT 0,
  is_verified TINYINT DEFAULT 0 COMMENT '是否平台认证',
  verified_at TIMESTAMP NULL,
  status TINYINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_location (longitude, latitude),
  KEY idx_geohash (geohash),
  KEY idx_type_city (poi_type, city),
  KEY idx_pet_level (pet_level),
  FULLTEXT KEY ft_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='POI地点表';
