-- 创建文章表（用于内容管理和狗狗回顾）
CREATE TABLE IF NOT EXISTS articles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL COMMENT '文章标题',
  subtitle VARCHAR(500) NULL COMMENT '副标题',
  cover_image VARCHAR(500) NULL COMMENT '封面图',
  summary VARCHAR(1000) NULL COMMENT '摘要',
  content MEDIUMTEXT NOT NULL COMMENT '文章内容',
  category VARCHAR(50) DEFAULT 'travel' COMMENT '分类: travel旅行 guide攻略 story故事 review回顾',
  tags VARCHAR(500) NULL COMMENT '标签,逗号分隔',
  author_id INT DEFAULT 0 COMMENT '作者ID',
  author_name VARCHAR(50) NULL COMMENT '作者名',
  location VARCHAR(200) NULL COMMENT '活动地点',
  event_date VARCHAR(50) NULL COMMENT '活动日期',
  participants INT DEFAULT 0 COMMENT '参与数量',
  view_count INT DEFAULT 0 COMMENT '浏览量',
  like_count INT DEFAULT 0 COMMENT '点赞数',
  collect_count INT DEFAULT 0 COMMENT '收藏数',
  status TINYINT DEFAULT 0 COMMENT '0草稿 1已发布 2下架',
  is_top TINYINT DEFAULT 0 COMMENT '0普通 1置顶',
  sort_order INT DEFAULT 0 COMMENT '排序',
  publish_time TIMESTAMP NULL COMMENT '发布时间',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_category_status (category, status),
  KEY idx_status (status),
  KEY idx_is_top (is_top),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文章表';
